// City name to query the places based on
export const CITY_NAME = "austin";

// Categories for each page of the APP to filter places based on
export const PLACESTOEAT_CATEGORY_NAMES = ["RESTURANTS", "VEGETARIAN", "SMOOTHIES", "STEAKHOUSES", "BBQ", "MEXIAN & TEX-MEX", "FOOD TRAILERS!", "INDIAN", "ASIAN/SUSHI", "BREAKFAST", "BRUNCH", "ITALIAN/PIZZA"];
export const SHOPLOCAL_CATEGORY_NAMES = ["SHOP", "COWBOY BOOTS", "BOOTS", "LOCAL SHOPS"];
export const NIGHTLIFE_CATEGORY_NAMES = ["NIGHTLIFE","BARS", "BREWWEIES", "DISTILLERIES", "ENTERTAINMENT DISTRICTS", "LIVE MUSIC"];
export const OUTDOORS_CATEGORY_NAMES = ["OUTDOORS", "GOLF", "HIKING AND BIKING", "LAKES AND BOATING", "LEASH FREE DOG PARKS", "PARKS AND SWIMMING", "TENNIS"];